### ISSUE TITLE
Use of wildcards in Datagrabber.

### ISSUE THREAD

**Issue by doreenr** [gablab/analysis#1]
The datagrabber version of the preprocessing workflow '7757e[...]'  does not seem to allow the use of wildcards such as '[1,2]' or '*' currently.

**Comment by tylerper** [comment]
I have been using wildcards in the preprocessing bips workflow (7757) for quite some time.  Could you point me to the location of your json file?

**Comment by doreenr** [comment]
Yes, it worked for me, too - until very recently. 

/gablab/p/eegfmri/configs/fobjects/Step1_faces_preproc_77_1.json

**Comment by tylerper** [comment]
Sorry for the delay, I wanted to run it as a single thread to watch for errors.  I just finished running that workflow here /tmp/tkp/ and it completed for both the subjects without error.  Perhaps you could post the error messages you're getting? (or try again?)

**Comment by doreenr** [comment]
Oh, I got it to run now, too. The "Check" button function still generates a "does NOT exist" for all filenames including wildcards, but I guess this is not as relevant at this point (and it may had this bug before). 

Thank you!
